<?php
declare(strict_types=1);

// BudFinancialData SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BudFinancialDataUtility::setRegistrar(function (BudFinancialDataUtility $u): void {
    $u->clean = [BudFinancialDataClean::class, 'call'];
    $u->done = [BudFinancialDataDone::class, 'call'];
    $u->make_error = [BudFinancialDataMakeError::class, 'call'];
    $u->feature_add = [BudFinancialDataFeatureAdd::class, 'call'];
    $u->feature_hook = [BudFinancialDataFeatureHook::class, 'call'];
    $u->feature_init = [BudFinancialDataFeatureInit::class, 'call'];
    $u->fetcher = [BudFinancialDataFetcher::class, 'call'];
    $u->make_fetch_def = [BudFinancialDataMakeFetchDef::class, 'call'];
    $u->make_context = [BudFinancialDataMakeContext::class, 'call'];
    $u->make_options = [BudFinancialDataMakeOptions::class, 'call'];
    $u->make_request = [BudFinancialDataMakeRequest::class, 'call'];
    $u->make_response = [BudFinancialDataMakeResponse::class, 'call'];
    $u->make_result = [BudFinancialDataMakeResult::class, 'call'];
    $u->make_point = [BudFinancialDataMakePoint::class, 'call'];
    $u->make_spec = [BudFinancialDataMakeSpec::class, 'call'];
    $u->make_url = [BudFinancialDataMakeUrl::class, 'call'];
    $u->param = [BudFinancialDataParam::class, 'call'];
    $u->prepare_auth = [BudFinancialDataPrepareAuth::class, 'call'];
    $u->prepare_body = [BudFinancialDataPrepareBody::class, 'call'];
    $u->prepare_headers = [BudFinancialDataPrepareHeaders::class, 'call'];
    $u->prepare_method = [BudFinancialDataPrepareMethod::class, 'call'];
    $u->prepare_params = [BudFinancialDataPrepareParams::class, 'call'];
    $u->prepare_path = [BudFinancialDataPreparePath::class, 'call'];
    $u->prepare_query = [BudFinancialDataPrepareQuery::class, 'call'];
    $u->graphql_body = [BudFinancialDataGraphql::class, 'body'];
    $u->graphql_errors = [BudFinancialDataGraphql::class, 'errors'];
    $u->result_basic = [BudFinancialDataResultBasic::class, 'call'];
    $u->result_body = [BudFinancialDataResultBody::class, 'call'];
    $u->result_headers = [BudFinancialDataResultHeaders::class, 'call'];
    $u->transform_request = [BudFinancialDataTransformRequest::class, 'call'];
    $u->transform_response = [BudFinancialDataTransformResponse::class, 'call'];
});
